// github-media.ts
// Pushes generated media files to Draguniteus/sparkie-studio-media
// and returns a permanent raw.githubusercontent.com URL.
// Non-blocking: if push fails, caller should fall back to original URL.

const MEDIA_REPO_OWNER = 'Draguniteus'
const MEDIA_REPO_NAME = 'sparkie-studio-media'
const MEDIA_REPO_BRANCH = 'main'

type MediaType = 'audio' | 'video'

interface PushResult {
  url: string
  filename: string
}

// Fetch bytes from an http/https URL
async function fetchBytes(url: string): Promise<Buffer> {
  const res = await fetch(url, { signal: AbortSignal.timeout(60000) })
  if (!res.ok) throw new Error('fetch failed: ' + res.status)
  return Buffer.from(await res.arrayBuffer())
}

// Extract bytes from a data: URL (data:type/ext;base64,...)
function bytesFromDataUrl(dataUrl: string): Buffer {
  const comma = dataUrl.indexOf(',')
  if (comma === -1) throw new Error('Invalid data URL')
  const b64 = dataUrl.slice(comma + 1)
  return Buffer.from(b64, 'base64')
}

export async function pushMediaToGitHub(
  mediaType: MediaType,
  sourceUrl: string,   // http URL or data: URL
  userId: string,
  ext: 'mp3' | 'mp4' = mediaType === 'audio' ? 'mp3' : 'mp4',
): Promise<PushResult> {
  const token = process.env.GITHUB_MEDIA_TOKEN
  if (!token) throw new Error('GITHUB_MEDIA_TOKEN not configured')

  // Resolve bytes
  let bytes: Buffer
  if (sourceUrl.startsWith('data:')) {
    bytes = bytesFromDataUrl(sourceUrl)
  } else {
    bytes = await fetchBytes(sourceUrl)
  }

  const safeUserId = (userId || 'anon').replace(/[^a-zA-Z0-9]/g, '').slice(0, 12)
  const filename = Date.now() + '-' + safeUserId + '.' + ext
  const filePath = mediaType + '/' + filename
  const b64Content = bytes.toString('base64')

  // GitHub Contents API — create file
  const apiUrl = 'https://api.github.com/repos/' + MEDIA_REPO_OWNER + '/' + MEDIA_REPO_NAME + '/contents/' + filePath

  const res = await fetch(apiUrl, {
    method: 'PUT',
    headers: {
      'Authorization': 'Bearer ' + token,
      'Content-Type': 'application/json',
      'X-GitHub-Api-Version': '2022-11-28',
    },
    body: JSON.stringify({
      message: 'media: ' + mediaType + ' generated by sparkie',
      content: b64Content,
      branch: MEDIA_REPO_BRANCH,
    }),
    signal: AbortSignal.timeout(30000),
  })

  if (!res.ok) {
    const err = await res.json().catch(() => ({}))
    throw new Error('GitHub push failed ' + res.status + ': ' + JSON.stringify(err))
  }

  const rawUrl = 'https://raw.githubusercontent.com/' + MEDIA_REPO_OWNER + '/' + MEDIA_REPO_NAME + '/' + MEDIA_REPO_BRANCH + '/' + filePath
  return { url: rawUrl, filename }
}
