name: sparkie-studio
services:
  - name: sparkie-studio
    github:
      repo: Draguniteus/sparkie-studio
      branch: master
      deploy_on_push: true
    source_dir: /
    environment_slug: node-js
    run_command: npm start
    http_port: 3000
    instance_size_slug: apps-s-1vcpu-1gb
    instance_count: 2
databases:
  - name: sparkie-db
    engine: PG
    version: "17"
region: nyc
