"use client"

import { useAppStore } from "@/store/appStore"
import { Download, FileCode, Clock, MessageSquare, Trash2 } from "lucide-react"

function getFileExtension(name: string): string {
  return name.split('.').pop()?.toUpperCase() || 'FILE'
}

function formatTime(date: Date): string {
  const d = new Date(date)
  return d.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true })
}

function formatDate(date: Date): string {
  const d = new Date(date)
  const today = new Date()
  const isToday = d.toDateString() === today.toDateString()
  return isToday ? 'Today' : d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
}

export function AssetsTab() {
  const { assets, clearAssets, setCurrentChat, currentChatId } = useAppStore()

  function downloadAsset(name: string, content: string) {
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = name
    a.click()
    URL.revokeObjectURL(url)
  }

  function getLangColor(lang: string): string {
    const colors: Record<string, string> = {
      html: 'text-orange-400',
      css: 'text-blue-400',
      js: 'text-yellow-400',
      jsx: 'text-cyan-400',
      ts: 'text-blue-300',
      tsx: 'text-cyan-300',
      py: 'text-green-400',
      json: 'text-gray-300',
    }
    return colors[lang.toLowerCase()] || 'text-honey-500'
  }

  if (assets.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center h-full px-6 py-12 text-center">
        <FileCode size={32} className="mb-3 text-honey-500/30" />
        <p className="text-sm font-medium text-text-secondary mb-1">No assets yet</p>
        <p className="text-[11px] text-text-muted">
          Files generated by Sparkie will appear here with their source chat and download link.
        </p>
      </div>
    )
  }

  // Group by date
  const grouped: Record<string, typeof assets> = {}
  assets.slice().reverse().forEach(asset => {
    const key = formatDate(asset.createdAt)
    if (!grouped[key]) grouped[key] = []
    grouped[key].push(asset)
  })

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="flex items-center justify-between px-3 py-2 border-b border-hive-border">
        <span className="text-[11px] text-text-muted font-medium uppercase tracking-wider">
          {assets.length} file{assets.length !== 1 ? 's' : ''}
        </span>
        <button
          onClick={clearAssets}
          className="text-[10px] text-text-muted hover:text-accent-error transition-colors flex items-center gap-1"
          title="Clear all assets"
        >
          <Trash2 size={11} />
          Clear
        </button>
      </div>

      {/* Asset list */}
      <div className="flex-1 overflow-y-auto">
        {Object.entries(grouped).map(([date, dateAssets]) => (
          <div key={date}>
            <div className="px-3 py-1.5 text-[10px] font-medium text-text-muted uppercase tracking-wider bg-hive-700/50 sticky top-0">
              {date}
            </div>
            {dateAssets.map(asset => {
              const ext = getFileExtension(asset.name)
              const langColor = getLangColor(asset.name.split('.').pop() || '')
              return (
                <div
                  key={asset.id}
                  className="group flex items-center gap-2.5 px-3 py-2.5 hover:bg-hive-hover transition-colors border-b border-hive-border/40"
                >
                  {/* File type badge */}
                  <div className={`w-9 h-9 rounded-md bg-hive-elevated flex items-center justify-center shrink-0 ${langColor} font-mono text-[9px] font-bold border border-hive-border`}>
                    {ext.slice(0, 4)}
                  </div>

                  {/* File info */}
                  <div className="flex-1 min-w-0">
                    <div className="text-xs font-medium text-text-primary truncate">{asset.name}</div>
                    <div className="flex items-center gap-2 mt-0.5">
                      <div className="flex items-center gap-1 text-[10px] text-text-muted">
                        <MessageSquare size={9} />
                        <span className="truncate max-w-[100px]">{asset.chatTitle}</span>
                      </div>
                      <div className="flex items-center gap-1 text-[10px] text-text-muted">
                        <Clock size={9} />
                        <span>{formatTime(asset.createdAt)}</span>
                      </div>
                    </div>
                  </div>

                  {/* Actions */}
                  <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                    <button
                      onClick={() => downloadAsset(asset.name, asset.content)}
                      className="p-1.5 rounded-md hover:bg-hive-elevated text-text-muted hover:text-honey-500 transition-colors"
                      title="Download"
                    >
                      <Download size={13} />
                    </button>
                  </div>
                </div>
              )
            })}
          </div>
        ))}
      </div>
    </div>
  )
}
